#!/bin/sh
if ! which black isort mypy pyflakes >/dev/null; then
    echo "can't find stuff, is venv active?"
    exit 1
fi
black pyoomph oomphmini
isort pyoomph oomphmini
mypy pyoomph oomphmini
pyflakes pyoomph oomphmini
