#!/bin/sh
# Can be used in two ways, './lint' or './lint --check'
if ! which black isort mypy pyflakes >/dev/null; then
    echo "can't find stuff, is venv active?"
    exit 1
fi
black pyoomph "$@" || error=yes
isort pyoomph "$@" || error=yes
mypy pyoomph || error=yes
pyflakes pyoomph || error=yes
[ "$error" != yes ] || exit 1
