#!/bin/bash
# Make sure self-hosted compiler can do something to all oomph files, including itself.
# Currently, it tokenizes them all.

set -e

make oomphc
for file in builtins.oomph tests/*.oomph self_hosted/*.oomph; do
    if [ $file == tests/unterminated_string_error.oomph ]; then
        # tokenizing fails, as supposed to
        continue
    fi

    echo $file
    ./oomphc --ast $file >/dev/null
done

echo "
================== success =================="
