#!/bin/bash
# Make sure self-hosted compiler can do something to all oomph files, including itself.
# Currently, it tokenizes them all.

set -e

python3 -m pyoomph oomph/main.oomph -o oomphc
for file in builtins.oomph tests/*.oomph oomph/*.oomph; do
    echo $file
    ./oomphc --tokens $file >/dev/null
done

echo "

================== success =================="
