on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: "3.9"
    - run: pip install -r requirements.txt
    - run: ./lint --check
  build:
    strategy:
      matrix:
        compiler: ["gcc", "tinycc/tcc"]
        python: ["3.7", "3.8", "3.9"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - run: pip install -r requirements.txt
    - run: sudo apt install gcc
#    - if: contains(['tinycc/tcc'], matrix.compiler)
#      run: |
#        git clone https://github.com/TinyCC/tinycc/
#        cd tinycc
#        git checkout aa77279
#        # For some reason, it has to be 'make install'ed somewhere.
#        # Otherwise it doesn't find header files.
#        ./configure --cc=gcc --prefix=$PWD/build
#        make -j2
#        make install
    - run: CC=${{ matrix.compiler }} make
    - run: ./test
  lexer_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: "3.9"
    - run: pip install -r requirements.txt
    - run: pip install pygments
    - shell: bash
      run: |
        for file in tests/*.oomph self_hosted/*.oomph; do
          echo $file
          python3 -m pygments -x -l oomph_pygments_lexer.py $file > out
          # https://superuser.com/a/380778
          sed -i 's/\x1b\[[0-9;]*m//g' out
          if [ $file == tests/no_trailing_newline.oomph ]; then
            # Pygments adds trailing newline, diff doesn't like it
            # https://unix.stackexchange.com/a/254753
            truncate -s -1 out
          fi
          diff $file out
        done
